### ISSUE TITLE
[Bug] Facts gathering needs python2 which is installed after facts gathering

### ISSUE THREAD

**Issue by Remy-Luciani** [tcheymol/generator-loopback-ansible#15]
I encountered this issue while provisioning an AWS EC2 instance with an Ubuntu 16.04 LTS which has python3 installed only in the default distribution.

Other people have a workaround: https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f

There are two main solutions:

1. Disable fact gathering, install python 2.7 in a pre_task, then ask for setup which implies Fact Gathering.
2. Use python3 as ansible_python_interpreter

I had an issue with solution 2 because the psycopg2 module was missing in python3. Ansible was not able to connect to the PostgreSQL DB.

@tcheymol @cRicateau what do you think about implementing solution 1?

**Comment by cRicateau** [comment]
resolved #19

**Comment by cRicateau** [comment]
resolved #19
